# Generated by Django 3.1.1 on 2020-09-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(related_name='players', to='main_app.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contenders',
            field=models.ManyToManyField(related_name='contenders', to='main_app.Profile'),
        ),
    ]
