# Generated by Django 3.1.1 on 2020-09-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200921_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(choices=[('D3.5', 'Dungeons & Dragons 3.5'), ('D5', 'Dungeons & Dragons 5'), ('P', 'Pathfinder'), ('C', 'Call of Cthulu'), ('S', 'Starfinder'), ('V', 'Vampire: the Masquerade')], max_length=100),
        ),
    ]
