# Generated by Django 3.0.8 on 2020-09-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200922_0139'),
        ('main_app', '0004_auto_20200921_2251'),
    ]

    operations = [
    ]
