# Generated by Django 3.1.1 on 2020-09-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200922_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='details',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='group',
            name='looking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
