# Generated by Django 3.0.8 on 2020-09-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200922_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('Bard', 'https://i.imgur.com/rPQXpUG.jpg?1'), ('Ranger', 'https://i.imgur.com/rPQXpUG.jpg?1')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of next session'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
