# Generated by Django 3.0.8 on 2020-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200924_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contenders',
            field=models.ManyToManyField(blank=True, related_name='contenders', to='main_app.Profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to='main_app.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='systems',
            field=models.ManyToManyField(blank=True, to='main_app.System'),
        ),
    ]
