# Generated by Django 3.0.8 on 2020-09-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200924_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('Rogue', 'https://i.imgur.com/AHgUoIv.png'), ('Barbarian (F)', 'https://i.imgur.com/zBHhmmr.png'), ('Wizard', 'https://i.imgur.com/EyeEo9D.png'), ('Prince', 'https://i.imgur.com/tWmY2sU.png'), ('Princess', 'https://i.imgur.com/F8k6i3d.png'), ('Bard', 'https://i.imgur.com/oE7KZOm.png'), ('Knight', 'https://i.imgur.com/x0q6FSr.png'), ('Monk', 'https://i.imgur.com/3XXKzWP.png'), ('Barbarian (M)', 'https://i.imgur.com/hyiR7Mi.png'), ('Maiden', 'https://i.imgur.com/9mXtSfN.png'), ('Queen', 'https://i.imgur.com/EO2FsmV.png')], max_length=255),
        ),
    ]
