# Generated by Django 3.1.1 on 2020-09-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200924_2235'),
        ('main_app', '0009_auto_20200924_2139'),
    ]

    operations = [
    ]
