# Generated by Django 3.0.8 on 2020-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200925_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, choices=[('Rogue', 'https://i.imgur.com/AHgUoIv'), ('https://i.imgur.com/zBHhmmr', 'Barbarian (F)'), ('https://i.imgur.com/EyeEo9D', 'Wizard'), ('https://i.imgur.com/tWmY2sU', 'Prince'), ('https://i.imgur.com/F8k6i3d', 'Princess'), ('https://i.imgur.com/oE7KZOm', 'Bard'), ('https://i.imgur.com/x0q6FSr', 'Knight'), ('https://i.imgur.com/3XXKzWP', 'Monk'), ('https://i.imgur.com/hyiR7Mi', 'Barbarian (M)'), ('https://i.imgur.com/9mXtSfN', 'Maiden'), ('https://i.imgur.com/EO2FsmV', 'Queen')], max_length=255),
        ),
    ]
