# Generated by Django 3.1.1 on 2020-09-20 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of next session')),
                ('location', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=2000)),
                ('avatar', models.CharField(choices=[('Bard', 'https://i.imgur.com/rPQXpUG.jpg?1'), ('Ranger', 'https://i.imgur.com/rPQXpUG.jpg?1')], max_length=255)),
                ('systems', models.ManyToManyField(to='main_app.System')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of next session')),
                ('location', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=2000)),
                ('group_name', models.CharField(max_length=100)),
                ('looking', models.BooleanField()),
                ('contenders', models.ManyToManyField(to='main_app.Profile')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.system')),
            ],
        ),
    ]
